export interface Product {
  id: string;
  name: string;
  genericName?: string;
  price: number;
  category: string;
  image: string;
  rating: number;
  reviewCount: number;
  badge?: string;
  description: string;
  details: string[];
  dosage?: string;
  manufacturer: string;
  inStock: boolean;
  requiresPrescription: boolean;
}

export const CATEGORIES = [
  'All',
  'Pain Relief',
  'Antibiotics',
  'Vitamins & Supplements',
  'Allergy & Sinus',
  'Diabetes Care',
  'Heart & Blood Pressure',
  'Digestive Health',
  'Cold & Flu',
  'Skin & Dermatology',
  'Eye & Ear Care',
  'Medical Devices',
] as const;

export const ALL_PRODUCTS: Product[] = [
  // ─── Pain Relief ─────────────────────────────────────────────────
  {
    id: '1',
    name: 'Paracetamol 500mg Tablets',
    genericName: 'Acetaminophen',
    price: 4.99,
    category: 'Pain Relief',
    image: '',
    rating: 4.8,
    reviewCount: 1204,
    badge: 'Best Seller',
    description:
      'Fast-acting paracetamol for effective relief of mild to moderate pain including headaches, toothaches, backaches, menstrual cramps, and fever. Gentle on the stomach compared to NSAIDs.',
    details: [
      'Active ingredient: Paracetamol 500mg',
      'Suitable for adults and children 12+',
      'Works within 30–45 minutes',
      'Does not cause stomach irritation',
      'Pack of 24 tablets',
      'Max 8 tablets per day',
    ],
    dosage: '1–2 tablets every 4–6 hours. Max 8 tablets/day.',
    manufacturer: 'GlaxoSmithKline',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '2',
    name: 'Ibuprofen 400mg Tablets',
    genericName: 'Ibuprofen',
    price: 6.49,
    category: 'Pain Relief',
    image: '',
    rating: 4.7,
    reviewCount: 876,
    description:
      'Anti-inflammatory pain reliever for effective treatment of headaches, dental pain, period pain, rheumatic and muscular pain, back pain, neuralgia, and fever.',
    details: [
      'Active ingredient: Ibuprofen 400mg (NSAID)',
      'Anti-inflammatory, analgesic, antipyretic',
      'Effective against inflammation-based pain',
      'Take with food to reduce stomach upset',
      'Pack of 24 tablets',
      'Not suitable for those with peptic ulcers',
    ],
    dosage: '1 tablet every 4–6 hours. Max 3 tablets/day.',
    manufacturer: 'Nurofen / Reckitt Benckiser',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '3',
    name: 'Aspirin 75mg Dispersible Tablets',
    genericName: 'Acetylsalicylic Acid',
    price: 3.99,
    category: 'Pain Relief',
    image: '',
    rating: 4.6,
    reviewCount: 543,
    description:
      'Low-dose aspirin for prevention of blood clots in patients at risk of heart attack or stroke. Also used as an anti-platelet therapy under doctor supervision.',
    details: [
      'Active ingredient: Aspirin 75mg',
      'Low-dose for cardiovascular protection',
      'Dispersible formula — dissolve in water',
      'Anti-platelet action reduces clot risk',
      'Pack of 28 tablets',
      'Consult your doctor before starting',
    ],
    dosage: '1 tablet daily with water. Doctor supervision advised.',
    manufacturer: 'Bayer',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '4',
    name: 'Tramadol HCl 50mg Capsules',
    genericName: 'Tramadol Hydrochloride',
    price: 14.99,
    category: 'Pain Relief',
    image: '',
    rating: 4.5,
    reviewCount: 312,
    badge: 'Rx Only',
    description:
      'Prescription-only opioid analgesic for moderate to severe pain. Used post-surgically, for chronic pain conditions, or pain not adequately controlled by non-opioid analgesics.',
    details: [
      'Active ingredient: Tramadol HCl 50mg',
      'Centrally acting opioid analgesic',
      'For moderate to moderately severe pain',
      'Schedule IV controlled substance',
      'Pack of 30 capsules',
      'Prescription required — do not share',
    ],
    dosage: '50–100mg every 4–6 hours. Max 400mg/day.',
    manufacturer: 'Mundipharma',
    inStock: true,
    requiresPrescription: true,
  },

  // ─── Antibiotics ─────────────────────────────────────────────────
  {
    id: '5',
    name: 'Amoxicillin 500mg Capsules',
    genericName: 'Amoxicillin Trihydrate',
    price: 12.99,
    category: 'Antibiotics',
    image: '',
    rating: 4.7,
    reviewCount: 689,
    badge: 'Rx Only',
    description:
      'Broad-spectrum penicillin antibiotic for bacterial infections including ear, nose and throat infections, chest infections, urinary tract infections, and skin infections.',
    details: [
      'Active ingredient: Amoxicillin 500mg',
      'Broad-spectrum penicillin-class antibiotic',
      'Effective against gram-positive & gram-negative bacteria',
      'Complete the full course even if feeling better',
      'Pack of 21 capsules (7-day course)',
      'Prescription required',
    ],
    dosage: '500mg three times daily for 7 days or as prescribed.',
    manufacturer: 'Sandoz / Novartis',
    inStock: true,
    requiresPrescription: true,
  },
  {
    id: '6',
    name: 'Azithromycin 250mg Tablets',
    genericName: 'Azithromycin Dihydrate',
    price: 18.5,
    category: 'Antibiotics',
    image: '',
    rating: 4.8,
    reviewCount: 471,
    badge: 'Rx Only',
    description:
      'Macrolide antibiotic for community-acquired pneumonia, acute exacerbations of COPD, pharyngitis, sinusitis, and skin infections. Convenient 5-day or 3-day dosing regimens.',
    details: [
      'Active ingredient: Azithromycin 250mg',
      'Macrolide antibiotic — once-daily dosing',
      'Long tissue half-life (5 days of coverage)',
      'Suitable for penicillin-allergic patients',
      'Pack of 6 tablets (Z-pack)',
      'Prescription required',
    ],
    dosage: 'Day 1: 500mg, Days 2–5: 250mg once daily.',
    manufacturer: 'Pfizer (Zithromax)',
    inStock: true,
    requiresPrescription: true,
  },
  {
    id: '7',
    name: 'Metronidazole 400mg Tablets',
    genericName: 'Metronidazole',
    price: 8.99,
    category: 'Antibiotics',
    image: '',
    rating: 4.5,
    reviewCount: 298,
    badge: 'Rx Only',
    description:
      'Antibiotic and antiprotozoal medication used to treat bacterial vaginosis, pelvic inflammatory disease, Clostridium difficile infection, and dental infections.',
    details: [
      'Active ingredient: Metronidazole 400mg',
      'Active against anaerobic bacteria & protozoa',
      'Used for dental, GI, and gynaecological infections',
      'Avoid alcohol during and 48hrs after treatment',
      'Pack of 21 tablets',
      'Prescription required',
    ],
    dosage: '400mg three times daily for 7 days.',
    manufacturer: 'Zentiva',
    inStock: true,
    requiresPrescription: true,
  },

  // ─── Allergy & Sinus ─────────────────────────────────────────────
  {
    id: '8',
    name: 'Cetirizine 10mg Tablets',
    genericName: 'Cetirizine Hydrochloride',
    price: 7.49,
    category: 'Allergy & Sinus',
    image: '',
    rating: 4.9,
    reviewCount: 1023,
    badge: 'Popular',
    description:
      'Non-drowsy, 24-hour antihistamine for hay fever, pet allergies, dust mite allergy, and urticaria (hives). Fast relief from sneezing, runny nose, and itchy, watery eyes.',
    details: [
      'Active ingredient: Cetirizine HCl 10mg',
      'Second-generation antihistamine — non-drowsy',
      '24-hour allergy relief from a single dose',
      'Relieves sneezing, itching, runny nose',
      'Pack of 30 tablets',
      'Suitable for adults and children 6+',
    ],
    dosage: '1 tablet once daily.',
    manufacturer: 'UCB Pharma (Zyrtec)',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '9',
    name: 'Loratadine 10mg Tablets',
    genericName: 'Loratadine',
    price: 5.99,
    category: 'Allergy & Sinus',
    image: '',
    rating: 4.6,
    reviewCount: 742,
    description:
      'Clinically proven, non-drowsy antihistamine for seasonal allergic rhinitis (hay fever) and chronic idiopathic urticaria. Starts working within 1–3 hours.',
    details: [
      'Active ingredient: Loratadine 10mg',
      'Non-sedating second-generation antihistamine',
      'Once daily dosing for 24-hour relief',
      'Suitable for adults and children 6+',
      'Pack of 30 tablets',
      'No-drowse formula — safe to drive',
    ],
    dosage: '1 tablet daily.',
    manufacturer: 'Schering-Plough (Claritin)',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '10',
    name: 'Fluticasone Nasal Spray 50mcg',
    genericName: 'Fluticasone Propionate',
    price: 11.99,
    category: 'Allergy & Sinus',
    image: '',
    rating: 4.8,
    reviewCount: 516,
    description:
      'Corticosteroid nasal spray for seasonal and perennial allergic rhinitis. Reduces nasal inflammation, congestion, sneezing, and runny nose. Most effective when used regularly.',
    details: [
      'Active ingredient: Fluticasone Propionate 50mcg/dose',
      'Corticosteroid — reduces nasal inflammation',
      'For hay fever and year-round allergies',
      'Takes 1–2 weeks for maximum effect',
      '150-dose pump bottle',
      'Suitable for adults and children 4+',
    ],
    dosage: '2 sprays per nostril once daily.',
    manufacturer: 'GSK (Flonase)',
    inStock: true,
    requiresPrescription: false,
  },

  // ─── Diabetes Care ────────────────────────────────────────────────
  {
    id: '11',
    name: 'Metformin 500mg Tablets',
    genericName: 'Metformin Hydrochloride',
    price: 9.99,
    category: 'Diabetes Care',
    image: '',
    rating: 4.7,
    reviewCount: 834,
    badge: 'Rx Only',
    description:
      'First-line oral antidiabetic medication for type 2 diabetes mellitus. Reduces hepatic glucose production and improves insulin sensitivity. Also used for PCOS management.',
    details: [
      'Active ingredient: Metformin HCl 500mg',
      'Biguanide class — reduces blood glucose',
      'Take with meals to reduce GI side effects',
      'Does not cause hypoglycaemia alone',
      'Pack of 60 tablets',
      'Prescription required — regular monitoring needed',
    ],
    dosage: '500mg twice daily with meals, titrated as needed.',
    manufacturer: 'Merck (Glucophage)',
    inStock: true,
    requiresPrescription: true,
  },
  {
    id: '12',
    name: 'Glibenclamide 5mg Tablets',
    genericName: 'Glibenclamide (Glyburide)',
    price: 11.49,
    category: 'Diabetes Care',
    image: '',
    rating: 4.4,
    reviewCount: 267,
    badge: 'Rx Only',
    description:
      'Sulfonylurea oral hypoglycaemic agent for type 2 diabetes. Stimulates the pancreas to produce more insulin. Used when diet, exercise, and metformin are insufficient.',
    details: [
      'Active ingredient: Glibenclamide 5mg',
      'Sulfonylurea class — stimulates insulin secretion',
      'Take 30 minutes before breakfast',
      'Risk of hypoglycaemia — monitor blood glucose',
      'Pack of 30 tablets',
      'Prescription required',
    ],
    dosage: '2.5–5mg daily before breakfast. Adjust per glucose levels.',
    manufacturer: 'Sanofi',
    inStock: true,
    requiresPrescription: true,
  },
  {
    id: '13',
    name: 'Accu-Chek Instant Blood Glucose Monitor',
    genericName: undefined,
    price: 34.99,
    category: 'Diabetes Care',
    image: '',
    rating: 4.8,
    reviewCount: 952,
    badge: 'New',
    description:
      'Smart blood glucose meter with Bluetooth connectivity and simple 3-step testing. Results in 4 seconds with no coding required. Compatible with the mySugr app for automatic logging.',
    details: [
      '4-second test results',
      'No coding required',
      'Bluetooth to mySugr app',
      'Small 0.6µL blood sample needed',
      'Stores 720 readings with date/time',
      'Includes 10 test strips and lancets',
    ],
    manufacturer: 'Roche Diagnostics',
    inStock: true,
    requiresPrescription: false,
  },

  // ─── Heart & Blood Pressure ───────────────────────────────────────
  {
    id: '14',
    name: 'Amlodipine 5mg Tablets',
    genericName: 'Amlodipine Besylate',
    price: 8.49,
    category: 'Heart & Blood Pressure',
    image: '',
    rating: 4.7,
    reviewCount: 618,
    badge: 'Rx Only',
    description:
      'Calcium channel blocker for hypertension (high blood pressure) and angina. Relaxes blood vessels to reduce blood pressure and the workload on the heart.',
    details: [
      'Active ingredient: Amlodipine 5mg',
      'Calcium channel blocker (CCB)',
      'Once-daily dosing for blood pressure control',
      'Also used for stable and vasospastic angina',
      'Pack of 30 tablets',
      'Prescription required — do not stop suddenly',
    ],
    dosage: '5mg once daily. May increase to 10mg.',
    manufacturer: 'Pfizer (Norvasc)',
    inStock: true,
    requiresPrescription: true,
  },
  {
    id: '15',
    name: 'Lisinopril 10mg Tablets',
    genericName: 'Lisinopril',
    price: 7.99,
    category: 'Heart & Blood Pressure',
    image: '',
    rating: 4.6,
    reviewCount: 489,
    badge: 'Rx Only',
    description:
      'ACE inhibitor for hypertension, heart failure, and post-myocardial infarction care. Protects kidneys in diabetic nephropathy. One of the most prescribed antihypertensives globally.',
    details: [
      'Active ingredient: Lisinopril 10mg',
      'ACE inhibitor — lowers blood pressure',
      'Cardioprotective post-heart attack',
      'Kidney-protective in diabetic patients',
      'Pack of 30 tablets',
      'Prescription required',
    ],
    dosage: '10mg once daily; range 10–40mg/day.',
    manufacturer: 'AstraZeneca (Zestril)',
    inStock: true,
    requiresPrescription: true,
  },
  {
    id: '16',
    name: 'Atorvastatin 20mg Tablets',
    genericName: 'Atorvastatin Calcium',
    price: 10.99,
    category: 'Heart & Blood Pressure',
    image: '',
    rating: 4.8,
    reviewCount: 731,
    badge: 'Rx Only',
    description:
      'HMG-CoA reductase inhibitor (statin) for reducing high cholesterol and triglycerides. Significantly lowers cardiovascular risk in patients with or at risk of coronary artery disease.',
    details: [
      'Active ingredient: Atorvastatin 20mg',
      'Statin — reduces LDL cholesterol',
      'Once daily dosing at any time of day',
      'Reduces risk of heart attack and stroke',
      'Pack of 30 tablets',
      'Prescription required — regular liver tests advised',
    ],
    dosage: '10–80mg once daily. Usual starting dose: 20mg.',
    manufacturer: 'Pfizer (Lipitor)',
    inStock: true,
    requiresPrescription: true,
  },

  // ─── Digestive Health ─────────────────────────────────────────────
  {
    id: '17',
    name: 'Omeprazole 20mg Capsules',
    genericName: 'Omeprazole',
    price: 9.49,
    category: 'Digestive Health',
    image: '',
    rating: 4.8,
    reviewCount: 892,
    badge: 'Popular',
    description:
      'Proton pump inhibitor (PPI) for gastro-oesophageal reflux disease (GERD), peptic ulcers, and H. pylori eradication. Reduces stomach acid production for long-lasting relief.',
    details: [
      'Active ingredient: Omeprazole 20mg',
      'Proton pump inhibitor (PPI)',
      'Effective for GERD, ulcers, heartburn',
      'Take 30–60 minutes before first meal',
      'Pack of 28 capsules',
      'OTC for short-term use; Rx for chronic use',
    ],
    dosage: '20mg once daily before breakfast for 2–4 weeks.',
    manufacturer: 'AstraZeneca (Losec/Prilosec)',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '18',
    name: 'Loperamide 2mg Capsules',
    genericName: 'Loperamide Hydrochloride',
    price: 4.99,
    category: 'Digestive Health',
    image: '',
    rating: 4.5,
    reviewCount: 374,
    description:
      'Fast-acting antidiarrhoeal medication that reduces bowel movement frequency and improves stool consistency. Suitable for acute and traveller\'s diarrhoea.',
    details: [
      'Active ingredient: Loperamide HCl 2mg',
      'Opioid receptor agonist — slows gut motility',
      'Acts within 1 hour of first dose',
      'Safe for adults and children 12+',
      'Pack of 12 capsules',
      'Do not use if blood or mucus in stool',
    ],
    dosage: 'Initially 2 capsules, then 1 after each loose stool. Max 8/day.',
    manufacturer: 'Johnson & Johnson (Imodium)',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '19',
    name: 'Lactulose Oral Solution 10g/15ml',
    genericName: 'Lactulose',
    price: 6.99,
    category: 'Digestive Health',
    image: '',
    rating: 4.3,
    reviewCount: 216,
    description:
      'Osmotic laxative for constipation and hepatic encephalopathy. Softens stools by drawing water into the bowel. Gentle and suitable for long-term use including in pregnancy.',
    details: [
      'Active ingredient: Lactulose 10g/15ml',
      'Osmotic laxative — draws water into colon',
      'Gentle, non-stimulant laxative',
      'Safe for long-term use and in pregnancy',
      '300ml bottle (~20 doses)',
      'May take 48 hours for first effect',
    ],
    dosage: '15–30ml once or twice daily. Adjust for response.',
    manufacturer: 'Fresenius Kabi',
    inStock: true,
    requiresPrescription: false,
  },

  // ─── Vitamins & Supplements ───────────────────────────────────────
  {
    id: '20',
    name: 'Vitamin D3 1000 IU Tablets',
    genericName: 'Cholecalciferol',
    price: 6.99,
    category: 'Vitamins & Supplements',
    image: '',
    rating: 4.8,
    reviewCount: 1431,
    badge: 'Best Seller',
    description:
      'Vitamin D3 supplementation for deficiency prevention and treatment. Essential for calcium absorption, bone health, immune function, and mood regulation. Especially important in low-sunlight regions.',
    details: [
      'Active ingredient: Cholecalciferol (Vitamin D3) 1000 IU',
      'Most bioavailable form of Vitamin D',
      'Supports bone, immune, and muscle health',
      'Recommended for UK/northern climates year-round',
      'Pack of 90 tablets',
      'Suitable for adults and children 5+',
    ],
    dosage: '1 tablet daily with food.',
    manufacturer: 'Holland & Barrett / Now Foods',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '21',
    name: 'Folic Acid 400mcg Tablets',
    genericName: 'Pteroylmonoglutamic Acid',
    price: 3.99,
    category: 'Vitamins & Supplements',
    image: '',
    rating: 4.9,
    reviewCount: 867,
    description:
      'Essential B-vitamin supplement for women trying to conceive and during early pregnancy. Reduces the risk of neural tube defects including spina bifida by up to 70%.',
    details: [
      'Active ingredient: Folic Acid 400mcg',
      'Essential for neural tube development',
      'Start 12 weeks before conception',
      'Continue through first 12 weeks of pregnancy',
      'Pack of 90 tablets',
      'NHS recommended — safe for daily use',
    ],
    dosage: '1 tablet daily. Start 3 months before conception.',
    manufacturer: 'Seven Seas / Boots',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '22',
    name: 'Omega-3 Fish Oil 1000mg Capsules',
    genericName: 'EPA/DHA Omega-3 Fatty Acids',
    price: 12.99,
    category: 'Vitamins & Supplements',
    image: '',
    rating: 4.6,
    reviewCount: 643,
    description:
      'High-strength Omega-3 fish oil with 300mg EPA+DHA per capsule. Supports cardiovascular health, brain function, joint mobility, and reduces inflammation. IFOS 5-star certified.',
    details: [
      'Active: EPA 180mg + DHA 120mg per capsule',
      'IFOS 5-star certified for purity',
      'Molecularly distilled — free from heavy metals',
      'Enteric coating prevents fishy aftertaste',
      'Pack of 90 softgels',
      'No artificial colours or flavours',
    ],
    dosage: '1–3 capsules daily with meals.',
    manufacturer: 'Seven Seas / Minami',
    inStock: true,
    requiresPrescription: false,
  },

  // ─── Cold & Flu ───────────────────────────────────────────────────
  {
    id: '23',
    name: 'Lemsip Max Cold & Flu Sachets',
    genericName: 'Paracetamol + Phenylephrine',
    price: 5.49,
    category: 'Cold & Flu',
    image: '',
    rating: 4.7,
    reviewCount: 987,
    badge: 'Popular',
    description:
      'All-in-one cold and flu remedy with paracetamol for pain and fever, phenylephrine for nasal decongestion, and Vitamin C. Hot lemon drink format for soothing relief.',
    details: [
      'Paracetamol 1000mg + Phenylephrine 12.2mg',
      'Relieves fever, headache, aches, blocked nose',
      'Contains Vitamin C 60mg',
      'Hot lemon drink format — soothing relief',
      'Pack of 10 sachets',
      'Do not take with other paracetamol products',
    ],
    dosage: '1 sachet in hot water every 4–6 hours. Max 4/day.',
    manufacturer: 'Reckitt Benckiser',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '24',
    name: 'Sudafed Blocked Nose Spray 0.1%',
    genericName: 'Xylometazoline HCl',
    price: 6.99,
    category: 'Cold & Flu',
    image: '',
    rating: 4.6,
    reviewCount: 423,
    description:
      'Fast-acting nasal decongestant spray for the symptomatic relief of nasal congestion caused by cold, flu, sinusitis, and hay fever. Acts in seconds, lasts up to 10 hours.',
    details: [
      'Active ingredient: Xylometazoline 0.1%',
      'Alpha-adrenergic agonist — constricts nasal vessels',
      'Works within seconds, lasts 8–10 hours',
      '10ml bottle (approx. 100 doses per nostril)',
      'Do not use for more than 7 consecutive days',
      'Not suitable for children under 12',
    ],
    dosage: '1–2 sprays per nostril up to 3× daily. Max 7 days.',
    manufacturer: 'Johnson & Johnson',
    inStock: true,
    requiresPrescription: false,
  },

  // ─── Skin & Dermatology ───────────────────────────────────────────
  {
    id: '25',
    name: 'Hydrocortisone 1% Cream',
    genericName: 'Hydrocortisone',
    price: 5.99,
    category: 'Skin & Dermatology',
    image: '',
    rating: 4.6,
    reviewCount: 598,
    description:
      'Mild topical corticosteroid for the relief of eczema, dermatitis, insect bites, and mild allergic skin reactions. Reduces redness, itching, and inflammation quickly.',
    details: [
      'Active ingredient: Hydrocortisone 1%',
      'Mild topical corticosteroid',
      'Treats eczema, dermatitis, insect bites',
      'Apply sparingly to affected area',
      '30g tube',
      'Do not apply to face, broken or infected skin',
    ],
    dosage: 'Apply thinly to affected area 2–3× daily for up to 7 days.',
    manufacturer: 'Dermacort / E45',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '26',
    name: 'Clotrimazole 1% Cream (Antifungal)',
    genericName: 'Clotrimazole',
    price: 7.49,
    category: 'Skin & Dermatology',
    image: '',
    rating: 4.7,
    reviewCount: 374,
    description:
      'Broad-spectrum antifungal cream for athlete\'s foot (tinea pedis), ringworm (tinea corporis), jock itch (tinea cruris), and candidal skin infections.',
    details: [
      'Active ingredient: Clotrimazole 1%',
      'Azole antifungal — disrupts fungal cell membrane',
      'Effective against dermatophytes and Candida',
      'Treats athlete\'s foot, ringworm, jock itch',
      '30g tube',
      'Continue 2 weeks after symptoms clear',
    ],
    dosage: 'Apply 2–3× daily for 2–4 weeks.',
    manufacturer: 'Bayer (Canesten)',
    inStock: true,
    requiresPrescription: false,
  },

  // ─── Eye & Ear Care ───────────────────────────────────────────────
  {
    id: '27',
    name: 'Sodium Chloride 0.9% Eye Drops',
    genericName: 'Sodium Chloride (Saline)',
    price: 4.49,
    category: 'Eye & Ear Care',
    image: '',
    rating: 4.5,
    reviewCount: 287,
    description:
      'Sterile isotonic saline eye drops for the relief of dry, irritated, and tired eyes. Also used for flushing out particles or contact-lens-related discomfort.',
    details: [
      'Active ingredient: Sodium Chloride 0.9%',
      'Isotonic — matches natural tear composition',
      'Preservative-free unit dose vials',
      'Suitable for use with contact lenses',
      'Pack of 30 × 0.5ml single-dose vials',
      'Safe for frequent use',
    ],
    dosage: '1–2 drops into affected eye(s) as needed.',
    manufacturer: 'Bausch & Lomb / Minims',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '28',
    name: 'Chloramphenicol 0.5% Eye Drops',
    genericName: 'Chloramphenicol',
    price: 6.49,
    category: 'Eye & Ear Care',
    image: '',
    rating: 4.6,
    reviewCount: 331,
    description:
      'Antibiotic eye drops for the treatment of acute bacterial conjunctivitis (pink eye). Broad-spectrum activity against most conjunctival bacteria. Available OTC in many countries.',
    details: [
      'Active ingredient: Chloramphenicol 0.5%',
      'Broad-spectrum antibiotic for bacterial conjunctivitis',
      'Effective against most common eye bacteria',
      'Do not wear contacts while using',
      '10ml dropper bottle',
      'Complete full 5-day course',
    ],
    dosage: '1–2 drops every 2 hours (first 2 days), then 4× daily.',
    manufacturer: 'Bausch & Lomb / Brocades',
    inStock: true,
    requiresPrescription: false,
  },

  // ─── Medical Devices ──────────────────────────────────────────────
  {
    id: '29',
    name: 'Omron M3 Upper Arm Blood Pressure Monitor',
    genericName: undefined,
    price: 49.99,
    category: 'Medical Devices',
    image: '',
    rating: 4.9,
    reviewCount: 1872,
    badge: 'Best Seller',
    description:
      'Clinically validated upper-arm blood pressure monitor with Intelli Wrap Cuff for accurate readings regardless of cuff placement. Detects irregular heartbeat and stores 60 readings per user (2 users).',
    details: [
      'Clinically validated (ESH/AAMI/BHS)',
      'Intelli Wrap Cuff — accurate at any angle',
      'Detects irregular heartbeat (IHB)',
      '2-user mode, 60 readings each',
      'WHO blood pressure indicator',
      'AC adapter and 4 AA batteries included',
    ],
    manufacturer: 'Omron Healthcare',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '30',
    name: 'Beurer Fingertip Pulse Oximeter PO30',
    genericName: undefined,
    price: 22.99,
    category: 'Medical Devices',
    image: '',
    rating: 4.7,
    reviewCount: 643,
    description:
      'Compact, clip-style pulse oximeter that measures blood oxygen saturation (SpO2) and pulse rate in under 10 seconds. Clear OLED display with 4 viewing angles. Ideal for home monitoring.',
    details: [
      'Measures SpO2 (70–99%) and pulse rate (30–250 bpm)',
      'OLED display — 4 orientation modes',
      'Results in under 10 seconds',
      'Auto power-off after 8 seconds',
      'Includes protective carry case and lanyard',
      'CE marked medical device',
    ],
    manufacturer: 'Beurer GmbH',
    inStock: true,
    requiresPrescription: false,
  },
  {
    id: '31',
    name: 'Braun ThermoScan 7 Ear Thermometer',
    genericName: undefined,
    price: 64.99,
    category: 'Medical Devices',
    image: '',
    rating: 4.8,
    reviewCount: 2104,
    badge: 'Popular',
    description:
      'Pre-Warmed Tip technology ensures accurate, fast readings every time. In-ear thermometer that displays temperature in 2 seconds and automatically indicates if a fever is present via colour-coded display.',
    details: [
      'Pre-Warmed Tip for clinic-level accuracy',
      'Results in 2 seconds',
      'Colour-coded fever guidance (green/yellow/red)',
      'Age-related fever guidance feature',
      'Memory for last 21 readings',
      'Includes 21 disposable lens filters',
    ],
    manufacturer: 'Braun / Procter & Gamble',
    inStock: true,
    requiresPrescription: false,
  },
];
